package cc.multee;

// Generated file

public enum Errors {
    SUCCESS(0),
    CORRUPT_UTF8(1),
    CORRUPT_JSON(2),
    CORRUPT_YAML(3),
    CORRUPT_URI(4),
    CORRUPT_BASE64(5),
    CORRUPT_HEX(6),
    JSON_KEY_NOT_FOUND(7),
    KMIP(10),
    SGX_INIT(20),
    SGX_ECALL(21),
    SGX_SEAL(22),
    SGX_KEY_DERIVATION(23),
    SGX_QE3(24),
    SGX_OCALL(25),
    SGX_REPORT(26),
    CREDENTIALS(31),
    CREDENTIALS_PINNING(32),
    CREDENTIALS_IO(33),
    ENCLAVE_ARTIFACT_IO(34),
    UNSUPPORTED_PLATFORM(35),
    API_MISUSE(36),
    LOG_IO(40),
    RUSTLS_IO(50),
    KEY_IMPORT(60),
    TRIPLE_A_NOK(61),
    TRIPLE_A_PROTOCOL_VIOLATION(62),
    CRYPTO_UNSUPPORTED_SCHEME_FOR_KEY_IMPORT(100),
    CRYPTO_UNSUPPORTED_CIPHER_MODE(101),
    CRYPTO_KEYS_ALREADY_IMPORTED(102),
    CRYPTO_UNEXPECTED_ALG_OR_LEN(104),
    CRYPTO_ALG_MISMATCH(105),
    CRYPTO_UNSUPPORTED_HASH(106),
    CRYPTO_PROHIBITED_USAGE(107),
    CRYPTO_AUTH_TAG_VERIFY_FAILED(108),
    CRYPTO_AUTH_TAG_LEN_MISMATCH(109),
    CRYPTO_MAC_LEN_MISMATCH(110),
    CRYPTO_CIPHERTEXT_LEN_MISMATCH(111),
    CRYPTO_BAD_PADDING(112),
    CRYPTO_BUFFER_TOO_SMALL(113),
    CRYPTO_INVALID_IV_LENGTH(114),
    CRYPTO_INVALID_KEY_INDEX(115),
    CRYPTO_INVALID_KEY_NAME(116),
    CRYPTO_INVALID_ARGUMENTS(117),
    CRYPTO_MBED(200),
    A3_ERROR(300),
    A3_WARNING(301),
    HTTP_MALFORMATTED_RESPONSE(70),
    MACHINE_INFO_NOT_FOUND(73),
    OBFUSCATION_FAILED(74),
    LAZY_CELL_FILLED(75),
    LAZY_CELL_EMPTY(76),
    PKCS11_PROTOCOL_VIOLATION(80),
    UNEXPECTED_OR_IMPOSSIBLE(90),
    SEVSNP_REPORT(150);

  final int code;

  Errors( final int v ) {
    this.code = v;
  }
}
