#ifndef MBEDTLS_CONFIG_H
#define MBEDTLS_CONFIG_H

#define MBEDTLS_ERROR_C
#define MBEDTLS_BASE64_C

#define MBEDTLS_PEM_WRITE_C
#define MBEDTLS_PEM_PARSE_C
#define MBEDTLS_X509_CREATE_C
#define MBEDTLS_X509_USE_C
#define MBEDTLS_X509_CHECK_EXTENDED_KEY_USAGE
#define MBEDTLS_X509_RSASSA_PSS_SUPPORT
#define MBEDTLS_X509_CSR_PARSE_C
#define MBEDTLS_X509_CSR_WRITE_C
#define MBEDTLS_X509_CHECK_KEY_USAGE
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_X509_CRT_WRITE_C
#define MBEDTLS_X509_CRL_PARSE_C
#define MBEDTLS_PK_WRITE_C
#define MBEDTLS_PK_PARSE_C
#define MBEDTLS_PK_PARSE_EC_EXTENDED
#define MBEDTLS_OID_C
#define MBEDTLS_ASN1_WRITE_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_PKCS12_C

#define MBEDTLS_CIPHER_MODE_CBC
#define MBEDTLS_CIPHER_MODE_CTR
#define MBEDTLS_GCM_C

#define MBEDTLS_ECDSA_C
#define MBEDTLS_ECP_C
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED // secp256r1, called prime256v1 in openssl
#define MBEDTLS_ECP_DP_SECP256K1_ENABLED
#define MBEDTLS_ECP_DP_SECP384R1_ENABLED
#define MBEDTLS_ECP_DP_SECP521R1_ENABLED

#define MBEDTLS_AES_C

#define MBEDTLS_MD_C
#define MBEDTLS_SHA512_C
#define MBEDTLS_SHA256_C

#define MBEDTLS_PKCS5_C
#define MBEDTLS_PKCS1_V21
#define MBEDTLS_PKCS1_V15
#define MBEDTLS_CIPHER_PADDING_PKCS7
#define MBEDTLS_GENPRIME
#define MBEDTLS_CIPHER_C
#define MBEDTLS_PK_C
#define MBEDTLS_BIGNUM_C
#define MBEDTLS_RSA_C
#define MBEDTLS_CTR_DRBG_C

#define MBEDTLS_HAVE_ASM
#define MBEDTLS_HAVE_SSE2

int mbedtls_aesni_has_support( unsigned int what ) __attribute__((weak));

#define MBEDTLS_THREADING_C
#define MBEDTLS_ENTROPY_C

#define MBEDTLS_ECP_NIST_OPTIM
#define MBEDTLS_NIST_KW_C

#if  defined(MULTEE_X86_SGX)
  #define MBEDTLS_AESNI_C
  #define MBEDTLS_THREADING_ALT
  #define MBEDTLS_ENTROPY_HARDWARE_ALT
  #define MBEDTLS_NO_PLATFORM_ENTROPY
#elif defined(MULTEE_X86_DEVM)
  #define MBEDTLS_AESNI_C
  #define MBEDTLS_THREADING_ALT
  #define MBEDTLS_NO_PLATFORM_ENTROPY
  #define MBEDTLS_TEST_NULL_ENTROPY
  #define MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES
#elif defined(MULTEE_X86_NOSGX)
  #define MBEDTLS_AESNI_C
  #define MBEDTLS_THREADING_PTHREAD
  #define MBEDTLS_HAVEGE_C
  #define MBEDTLS_TIMING_C
#else
  #error "TODO: support for non-x86_64 targets"
#endif

#include "mbedtls/check_config.h"

#endif /* MBEDTLS_CONFIG_H */

